

version: '3'
services:
  spring-app:
    image: money_transfer
    ports:
      - "8080:8080"
    extra_hosts:
      - "localhost:5500"
    networks:
      - backend

networks:
  backend:
    driver: bridge

